FROM --platform=linux/amd64 eclipse-temurin
#ARG JAR_FILE=target/*.jar
#COPY ${JAR_FILE} app.jar
COPY build/libs/SecureStore-0.1-SNAPSHOT.jar app.jar
COPY server.crt server.crt
COPY --chown=1001 runsecstorebe.sh runsecstorebe.sh
RUN chmod +x runsecstorebe.sh

EXPOSE 8580
ENTRYPOINT ["./runsecstorebe.sh"]